# Generated by Django 4.0.1 on 2022-03-25 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('agent_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('agent_office_name', models.CharField(max_length=50)),
                ('agent_office_address', models.CharField(max_length=50)),
                ('agent_office_contact', models.CharField(max_length=50)),
                ('agent_office_description', models.CharField(max_length=50)),
                ('agent_clients', models.ManyToManyField(related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('agent_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
