# Generated by Django 4.0.1 on 2022-03-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investmentid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('investmenttype', models.CharField(max_length=50)),
                ('investmentcompany', models.CharField(max_length=50)),
                ('investment_user_id', models.CharField(max_length=50)),
                ('investment_amount', models.CharField(max_length=50)),
                ('investment_date', models.DateField()),
                ('investment_due_date', models.DateField()),
                ('investment_lastupdate_date', models.DateField(auto_now=True)),
                ('investment_agent_id', models.CharField(max_length=50)),
                ('investment_description', models.CharField(max_length=50)),
            ],
        ),
    ]
