# Generated by Django 4.0.1 on 2022-03-25 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('Reminder_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Reminder_date', models.DateField()),
                ('Reminder_description', models.CharField(max_length=50)),
                ('Reminder_lastupdate_date', models.DateField(auto_now=True)),
                ('Reminder_lastupdate_user_id', models.IntegerField(null=True)),
                ('Reminder_Investment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment.investment')),
                ('Reminder_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
