# Generated by Django 4.0.1 on 2022-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilephoto',
            field=models.ImageField(blank=True, default='/static/assets/img/OIP.jpeg', null=True, upload_to=''),
        ),
    ]
