# Generated by Django 4.0.1 on 2022-04-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customuser_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilephoto',
            field=models.ImageField(blank=True, default='/media/Image/OIP.jpeg', upload_to='media/Image/'),
        ),
    ]
